### ISSUE TITLE
[1.19.2][Compatibility]: Create Deco

### ISSUE THREAD

**Issue by GamerTable** [JackGlobetrotter/Full-Slabs#18] opened 2023-11-27 01:06 UTC
### Full-Slabs Version

3.3.6

### Minecraft Version

1.19.2

### Fabric Loader Version

0.14.23

### Fabric API Version

0.76.1

### What happened?

Playing Alongside Create mod, Placed a vertical slab on Glued structure and the broke it, this caused a crash.
After logging into server again Crash persists.

### crash-log

https://gist.github.com/GamerTable/b092da2be0287f37e79f2926abe45180

### latest.log

https://gist.github.com/GamerTable/081afb1bf72d16a35c9e2f2328cce661

### Did you isolate Full-Slabs?

I did not try Full-Slabs alone

**Comment by JackGlobetrotter** [comment] 2023-11-27 10:45
This is a heavily modded game, please try to reproduce the error only with the offending mod installed (Create Mod). Please do also try the latest 1.20 version!

**Comment by GamerTable** [comment] 2023-11-28 20:52
Okay So I've narrowed down the issue, It's not an issue with Create Contraptions (Or Create at all really)
It's an issue with vertical slabs added by rogue mods. One of these happened to be a Create mod addon that I was using. 
(Sorry I tried it on 1.19.2 since it's the version my friends and I are using)
https://gist.github.com/GamerTable/29cefdce0c409cae31af6bbdb397f549

https://github.com/JackGlobetrotter/Full-Slabs/assets/114619268/257b4f58-3274-4cb8-913b-df2e677ae7b3

**Comment by GamerTable** [comment] 2023-11-28 21:04
I know you are updating only the latest versions but I would really appreciate a fix for 1.19,2

**Comment by JackGlobetrotter** [comment] 2023-11-29 00:57
Will have a look into it ! Just to be clear, explicitly coded vertical slaps won't be controllable by this mod (they will always stay vertical).

**Comment by GamerTable** [comment] 2023-11-29 01:07
Cool, Thanks man

**Comment by JackGlobetrotter** [comment] 2023-11-30 20:43
The crash happens because you try to place a Vertical slab horizontal. When you place it in the middle of the block (vertical) it wont crash. Won't fix any bugs occurring due to this mod as it does not provide accurate block models for the slabs and is impossible to debug, sorry

**Comment by GamerTable** [comment] 2023-11-30 21:33
Damn all good, Thanks for giving it a shot!

**Closed as completed** 2023-11-30 21:56 UTC
Labels: compatibility
